{{- $autoFlag := and .Values.coordinator.enabled (eq .Values.coordinator.catalog "katalog") }}
{{- if include "fybrik.isEnabled" (tuple .Values.katalogConnector.enabled $autoFlag) }}
# katalog-editor allows managing assets.
apiVersion: rbac.authorization.k8s.io/v1
{{- if .Values.clusterScoped }}
kind: ClusterRole
metadata:
  name: katalog-editor
{{- else }}
kind: Role
metadata:
  name: katalog-editor
  namespace: {{ .Values.applicationNamespace | default .Release.Namespace  }}
{{- end }}
rules:
- apiGroups: ["katalog.fybrik.io"]
  resources: ["assets"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete", "deletecollection"]
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete", "deletecollection"]
{{- end }}
