{{- $autoFlag := and .Values.coordinator.enabled (eq .Values.coordinator.catalog "katalog") }}
{{- if include "fybrik.isEnabled" (tuple .Values.katalogConnector.enabled $autoFlag) }}
apiVersion: v1
kind: Service
metadata:
  name: "katalog-connector"
  labels:
    app.kubernetes.io/component: katalog-connector
    {{- include "fybrik.labels" . | nindent 4 }}
spec:
  type: {{ .Values.katalogConnector.service.type }}
  ports:
    - port: {{ .Values.katalogConnector.service.port }}
      protocol: TCP
      {{- if .Values.katalogConnector.tls.use_tls }}
      name: https
      {{- else }}
      name: http
      {{- end }}
  selector:
    app.kubernetes.io/component: katalog-connector
    {{- include "fybrik.selectorLabels" . | nindent 4 }}
{{- end }}
