{{- $autoFlag := and .Values.coordinator.enabled (eq .Values.coordinator.catalog "katalog") }}
{{- if include "fybrik.isEnabled" (tuple .Values.katalogConnector.enabled $autoFlag) }}
# Grant katalog-connector the katalog-editor Role.
apiVersion: rbac.authorization.k8s.io/v1
{{- if .Values.clusterScoped }}
kind: ClusterRoleBinding
metadata:
  name:  katalog-connector-viewer
roleRef:
  kind: ClusterRole
{{- else }}
kind: RoleBinding
metadata:
  name:  katalog-connector-viewer
  namespace: {{ .Values.applicationNamespace | default .Release.Namespace  }}
roleRef:
  kind: Role
{{- end }}
  name: katalog-viewer
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: {{ .Values.katalogConnector.serviceAccount.name | default "default" }}
  namespace: {{ .Release.Namespace }}
{{- end }}
