{{- $autoFlag := and .Values.coordinator.enabled (eq .Values.coordinator.catalog "katalog") }}
{{- if include "fybrik.isEnabled" (tuple .Values.katalogConnector.enabled $autoFlag) }}
# katalog-editor allows managing assets and secrets if the connection between
# the manager and the katalog uses tls.
apiVersion: rbac.authorization.k8s.io/v1
{{- if .Values.clusterScoped }}
kind: ClusterRole
metadata:
  name: {{ template "fybrik.fullname" . }}-katalog-editor-cr
{{- else }}
kind: Role
metadata:
  name: {{ template "fybrik.fullname" . }}-katalog-editor-role
  namespace: {{ .Values.applicationNamespace | default .Release.Namespace  }}
{{- end }}
rules:
- apiGroups: ["katalog.fybrik.io"]
  resources: ["assets"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete", "deletecollection"]
{{- if .Values.katalogConnector.tls.use_tls }}
- apiGroups: [""]
  resources:
  - secrets
  verbs: ["get"]
{{- end }}
{{- end }}
