vault:
  server:
    dev:
      enabled: true
    # Enables a headless service to be used by the Vault Statefulset
    service:
      enabled: true
      type: NodePort
      nodePort: 31752
    extraArgs: '-dev-plugin-dir=/usr/local/libexec/vault'
    volumes:
      - name: plugins
        emptyDir: {}
    volumeMounts:
      - mountPath: /usr/local/libexec/vault
        name: plugins
        readOnly: false
    extraEnvironmentVars:
      OM_SERVER_URL: http://openmetadata.open-metadata:8585/api
    extraInitContainers:
      - name: kubesecrets-plugin
        image: ghcr.io/fybrik/vault-plugin-secrets-kubernetes-reader:0.5.0
        command: [/bin/sh, -ec]
        args:
          - cp /vault-plugin-secrets-kubernetes-reader /usr/local/libexec/vault/vault-plugin-secrets-kubernetes-reader
        volumeMounts:
        - name: plugins
          mountPath: /usr/local/libexec/vault
          readOnly: false
      - name: omd-secrets-plugin
        image: ghcr.io/fybrik/vault-plugin-secrets-omd-reader:0.1.0
        command: [/bin/sh, -ec]
        args:
          - cp /vault-plugin-secrets-omd-reader /usr/local/libexec/vault/vault-plugin-secrets-omd-reader
        volumeMounts:
        - name: plugins
          mountPath: /usr/local/libexec/vault
          readOnly: false
    # Used to define commands to run after the pod is ready.
    # This can be used to automate processes such as initialization
    # or boostrapping auth methods.
    postStart:
      - "sh"
      - "-c"
      # Sleep command is needed to avoid synchronization issues with the container pod. Please see
      # https://kubernetes.io/docs/tasks/configure-pod-container/attach-handler-lifecycle-event/#discussion
      # FIXME: Use a proper way to configure Vault after Vault start-up
      - |
        sleep 5
        SHA256=$(sha256sum /usr/local/libexec/vault/vault-plugin-secrets-kubernetes-reader | cut -d ' ' -f1) &&
        vault plugin register -sha256=$SHA256 secret vault-plugin-secrets-kubernetes-reader
        vault secrets enable -path=kubernetes-secrets vault-plugin-secrets-kubernetes-reader
        SHA256=$(sha256sum /usr/local/libexec/vault/vault-plugin-secrets-omd-reader | cut -d ' ' -f1) &&
        vault plugin register -sha256=$SHA256 secret vault-plugin-secrets-omd-reader
        vault secrets enable -path=omd-secrets vault-plugin-secrets-omd-reader
