{{- if or .Values.coordinator.enabled .Values.worker.enabled }}
{{- if .Values.modulesNamespace.managedByFybrik }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ include "fybrik.getModulesNamespace" . }}
{{- end }}
{{- end }}
