{{- if .Values.manager.enabled }}
{{- if .Values.applicationNamespace}}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ template "fybrik.fullname" . }}-applications-rb
  namespace: {{ .Values.applicationNamespace }}
  labels:
    {{- include "fybrik.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ template "fybrik.fullname" . }}-applications-role
subjects:
- kind: ServiceAccount
  name: {{ .Values.manager.serviceAccount.name | default "default" }}
  namespace: {{ .Release.Namespace }}
{{- end }}
{{- end }}
