{{- if .Values.manager.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: fybrik-config
data:
  PRETTY_LOGGING: {{ .Values.global.prettyLogging | quote }}
  LOGGING_VERBOSITY: {{ .Values.global.loggingVerbosity | quote }}
  
  {{- if .Values.coordinator.enabled }}
  DATAPATH_MAX_SIZE: {{ .Values.manager.dataPathMaxSize | quote }}
  CONNECTION_TIMEOUT: {{ .Values.manager.connectionTimeout | default .Values.global.connectionTimeout | quote }}
  CATALOG_PROVIDER_NAME: {{ .Values.coordinator.catalog | quote }}
  CATALOG_CONNECTOR_URL: {{ .Values.coordinator.catalogConnectorURL | default (printf "http://%s-connector:80" .Values.coordinator.catalog) | quote }}
  MAIN_POLICY_MANAGER_NAME: {{ .Values.coordinator.policyManager | quote }}
  MAIN_POLICY_MANAGER_CONNECTOR_URL: {{ .Values.coordinator.policyManagerConnectorURL | default (printf "http://%s-connector:80" .Values.coordinator.policyManager) | quote }}
  {{- if .Values.coordinator.vault.enabled }}
  VAULT_ENABLED: "true"
  VAULT_ADDRESS: {{ tpl .Values.coordinator.vault.address . | quote }}
  VAULT_MODULES_ROLE: "module" # temporary
  {{- end }}
  {{- end }}
{{- end }}
