{{- $autoFlag := and .Values.coordinator.enabled (eq .Values.coordinator.policyManager "opa") }}
{{- if include "fybrik.isEnabled" (tuple .Values.opaConnector.enabled $autoFlag) }}
# Grant opa-connector the opa-editor Role.
apiVersion: rbac.authorization.k8s.io/v1
{{- if .Values.clusterScoped }}
kind: ClusterRoleBinding
metadata:
  name:  {{ template "fybrik.fullname" . }}-opa-connector-crb
roleRef:
  kind: ClusterRole
  name: {{ template "fybrik.fullname" . }}-opa-editor-cr
{{- else }}
kind: RoleBinding
metadata:
  name:  {{ template "fybrik.fullname" . }}-opa-connector-rb
  namespace: {{ .Values.applicationNamespace | default .Release.Namespace  }}
roleRef:
  kind: Role
  name: {{ template "fybrik.fullname" . }}-opa-editor-role
{{- end }}
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: {{ .Values.opaConnector.serviceAccount.name | default "default" }}
  namespace: {{ .Release.Namespace }}
{{- end }}
