{{- $autoFlag := and .Values.coordinator.enabled (eq .Values.coordinator.catalog "openmetadata") }}
{{- if include "fybrik.isEnabled" (tuple .Values.openmetadataConnector.enabled $autoFlag) }}
{{- if .Values.openmetadataConnector.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.openmetadataConnector.serviceAccount.name }}
  labels:
    app.kubernetes.io/component: openmetadata-connector
    {{- include "fybrik.labels" . | nindent 4 }}
  {{- with .Values.openmetadataConnector.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
{{- end }}
