{{- if .Values.plugins.vaultPluginSecretsKubernetesReader.clusterScope }}
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: "vault-plugin-kubernetes-secret-reader-crb"
subjects:
- kind: ServiceAccount
  name: vault
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: vault-secrets-manager
  apiGroup: rbac.authorization.k8s.io
{{- end }}
